/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Christopher Lawrence
 */
public class APPLY_BANK_ACCOUNT extends javax.swing.JInternalFrame {

    /**
     * Creates new form APPLY_BANK_ACCOUNT
     */
    public APPLY_BANK_ACCOUNT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CREDIT = new javax.swing.JButton();
        DEBIT = new javax.swing.JButton();
        BACK = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE A CARD");

        CREDIT.setText("CREDIT");
        CREDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREDITActionPerformed(evt);
            }
        });

        DEBIT.setText("DEBIT");
        DEBIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEBITActionPerformed(evt);
            }
        });

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CREDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(DEBIT, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(410, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addComponent(CREDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(279, Short.MAX_VALUE)
                    .addComponent(DEBIT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(214, 214, 214)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DEBITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEBITActionPerformed
                javax.swing.JDesktopPane desktopPane = ((USER_MAIN_WINDOW) javax.swing.SwingUtilities.getWindowAncestor(this)).main_desktop;

    // Check if the FANTASY_GENRE_BOOKS internal frame is already opened
    for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
        if (frame instanceof DEBIT_VERIFICATION) {
            // If it's already open, bring it to the front
            try {
                frame.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
            return;  // Exit the method if the frame is already open
        }
    }

    // Create a new instance of the FANTASY_GENRE_BOOKS internal frame
    DEBIT_VERIFICATION romanceFrame = new DEBIT_VERIFICATION();

    // Add the internal frame to the JDesktopPane
    desktopPane.add(romanceFrame);

    // Make the internal frame visible
    romanceFrame.setVisible(true);

    // Optionally bring it to the front
    try {
        romanceFrame.setSelected(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_DEBITActionPerformed

    private void CREDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREDITActionPerformed
                        javax.swing.JDesktopPane desktopPane = ((USER_MAIN_WINDOW) javax.swing.SwingUtilities.getWindowAncestor(this)).main_desktop;

    // Check if the FANTASY_GENRE_BOOKS internal frame is already opened
    for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
        if (frame instanceof CREDIT_VERIFICATION) {
            // If it's already open, bring it to the front
            try {
                frame.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
            return;  // Exit the method if the frame is already open
        }
    }

    // Create a new instance of the FANTASY_GENRE_BOOKS internal frame
    CREDIT_VERIFICATION romanceFrame = new CREDIT_VERIFICATION();

    // Add the internal frame to the JDesktopPane
    desktopPane.add(romanceFrame);

    // Make the internal frame visible
    romanceFrame.setVisible(true);

    // Optionally bring it to the front
    try {
        romanceFrame.setSelected(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_CREDITActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        javax.swing.JDesktopPane desktopPane = ((USER_MAIN_WINDOW) javax.swing.SwingUtilities.getWindowAncestor(this)).main_desktop;

    // Check if the FANTASY_GENRE_BOOKS internal frame is already opened
    for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
        if (frame instanceof ACCOUNT_MANAGEMENT) {
            // If it's already open, bring it to the front
            try {
                frame.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
            return;  // Exit the method if the frame is already open
        }
    }

    // Create a new instance of the FANTASY_GENRE_BOOKS internal frame
    ACCOUNT_MANAGEMENT romanceFrame = new ACCOUNT_MANAGEMENT();

    // Add the internal frame to the JDesktopPane
    desktopPane.add(romanceFrame);

    // Make the internal frame visible
    romanceFrame.setVisible(true);

    // Optionally bring it to the front
    try {
        romanceFrame.setSelected(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_BACKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton CREDIT;
    private javax.swing.JButton DEBIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
